disabled_rules:
    # We avoid this well enough on our own that this is just annoying.
    - force_try

    # TODO notations are very handy.
    # We have a custom rule to force them to fit a specific format.
    - todo

    # With a capture list and args, it's sometimes useful to spill
    # over to the next line.
    - closure_parameter_position

    # This gripes about needlessly repeating `let` in if/guard, but that
    # is actually a requirement of Future Swift, so we *want* to do that.
    - conditional_binding_cascade

    # This is pretty baked-in to how we write code (and English prose!).
    # When we violate it, it's because we very much meant to.
    - comma

    # We do this right anyway, except when we're fighting Xcode on wrapping
    # tons o' arguments (thanks, UIKit!).
    - opening_brace

    # Sticking with |let| makes it easy to name this later.
    # |let| is also required to type-annotate the LHS.
    - redundant_discardable_let

    # Trailing commas reduce errors when appending to a collection,
    # as well as line-diffs if you push the closing bracket to next line.
    - trailing_comma

    # It's better to have the names there for documentation and future editing
    # than not. The closure body ought to be small enough to not matter that
    # a few extra names are around!
    - unused_closure_parameter

    # Prefer `if let _ = whatever` as a positive phrasing over the negative
    # `!= nil` variant.
    - unused_optional_binding

    # This obnoxiously expects you to write a doc comment for every blessed
    # parameter. This is a recipe for useless docs that just say the variable
    # name repeatedly.
    #
    # Plus, the warning is useless - it just gripes "Documented declarations
    # should be valid" without a hint about what "valid" means, or how your
    # current comment is invalid.
    #
    # See: https://github.com/realm/SwiftLint/issues/450
    - valid_docs

excluded:
    # Experiments are quick and dirty proofs of concept or "how do I?" demos.
    # They should not be linted.
    - experiments/
    - Carthage/

## Configuration for Inbuilt Rules ##
file_length:
    warning: 256
    error: 512

function_body_length:
    warning: 50
    error: 100

large_tuple:
    warning: 4
    error: 7

line_length:
    # This is to accommodate the UITableViewDataSource et al.'s long method names
    warning: 150
    error: 250

variable_name:
    excluded:
        - id
        - my
        - me

vertical_whitespace:
    max_empty_lines: 3

custom_rules:
    todo_format:
        match_kinds: comment
        message: >
            Prefix TODO/FIXME/etc with author and date,
            so if you're @example, then you'd write:
            // (@example/2016-07-28)TODO: Document custom rule
        # This isn't a perfect check, but it should guide folks the right
        # direction for common cases.
        regex: "[^)](TODO|FIXME|XXX|HACK|!{3}|[?]{3}):"
